config/routes.rb
Rails.application.routes.draw do
  #root to: 'toppages#index'
  root to: 'ctgs#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :ctgs
  resources :tchings do
    collection do
      get :search
      
    end
  end
  get 'signup', to: 'users#new' #ユーザの新規登録 URL を /signup にするため
  resources :users, only: [:index, :show, :new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ctg.rb
class Ctg < ApplicationRecord
    has_many :tchings, dependent: :destroy
    validates :ctg, presence: true, length: { maximum: 255 }
end

app/models/tching.rb
class Tching < ApplicationRecord
  belongs_to :ctg
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  validates :ctg_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
 before_save { self.email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
 include SessionsHelper
  
 private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/ctgs_controller.rb
class CtgsController < ApplicationController
  before_action :require_user_logged_in

 
  
  def index
    @ctgs = Ctg.order(id: :asc).page(params[:page]).per(20)
  
  end
 
  def new
     @ctg = Ctg.new
  end

  def create
    @ctg = Ctg.new(ctgs_params)
    if @ctg.save
      flash[:success] = 'カテゴリーが追加されました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'カテゴリーが追加されませんでした'
      render :new
    end
  end
  
  def edit
      @ctg = Ctg.find(params[:id]) 
  end

  def update
    @ctg = Ctg.find(params[:id]) 
    if @ctg.update(ctgs_params)
      flash[:success] = 'カテゴリーは正常に更新されました'
      redirect_to root_path
    else
      flash.now[:danger] = 'カテゴリーは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @ctg = Ctg.find(params[:id]) 
    @ctg.destroy

    flash[:success] = 'カテゴリーは正常に削除されました'
    redirect_to ctgs_url
 
  end
  
  private
  
  def ctgs_params
    params.require(:ctg).permit(:ctg)
     
  end
  
 

 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      #redirect_to controller: 'ctgs', action: 'index'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tchings_controller.rb
class TchingsController < ApplicationController
 
  def index
    @ctg = Ctg.find(params[:ctg_id])
    @tchings = @ctg.tchings.order(id: :asc).page(params[:page]).per(10)
    # @tchings = Tching.where(ctg_id: params[:ctg_id]).page(params[:page])
   
  end

  def search
    
    @keyw = params[:q]
    @tchings =Tching.where("content like '%" + @keyw + "%'").page(params[:page])
    
    render :serch
   
  end
  
  def show
    @tching = Tching.find(params[:id])
    @ctg_id = @tching.ctg_id
   
  end
  
  def new
     #@tching = Tching.new
     #@ctg = Ctg.find_by(params[:id])
     #@ctg = Ctg.where(ctg_id: params[:ctg_id])
     @tching = Tching.new(ctg_id: params[:ctg_id])
  end

  
  def create
    @tching = Tching.new(tching_params)
    if @tching.save
      flash[:success] = '正常に投稿されました'
      redirect_to @tching
    else
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end
  
  def edit
    
      @tching = Tching.find(params[:id]) 
      
  end

  def update
   @tching = Tching.find(params[:id]) 
    if @tching.update(tching_params)
      flash[:success] = '内容は正常に更新されました'
      redirect_to @tching
    else
      flash.now[:danger] = '内容は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @tching = Tching.find(params[:id]) 
    @ctg_id = @tching.ctg_id
    @tching.destroy
   
    flash[:success] = '内容は正常に削除されました'
    redirect_to tchings_url(ctg_id: @ctg_id)
    
    #redirect_to tchings_url
    #redirect_to tching_path(params[:id])
    #redirect_to root_path
    #redirect_to :action => 'index'
    
  end
 
  
  private
  
  def tching_params
    params.require(:tching).permit(:content, :title, :ctg_id)
  end
 
 
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
 before_action :require_user_logged_in, only: [:index, :show]
 
 def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end
  
 def show
    @user = User.find(params[:id])
 end
  
 def new
    @user = User.new
 end

 def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def destroy
  
      @user = User.find(params[:id])
      @user.destroy

    flash[:success] = 'ユーザーは正常に削除されました'
    redirect_to root_path
 
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
require "uri"
 
def text_url_to_link text
 
  URI.extract(text, ['http','https'] ).uniq.each do |url|
    sub_text = ""
    sub_text << "<a href=" << url << " target='_blank'>" << url << "</a>"
    text.gsub!(url, sub_text)
  end
 
  return text
end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ctgs/_form.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-sm-6">

<%= form_with(model: @ctg, local: true) do |f| %>

      <% if ctg.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% ctg.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
  

      <div class="form-group" >
      
       <%= f.text_field :ctg, class: "form-control" %>
      
      </div>
    
       <%= f.submit '登録',class: 'btn btn-primary btn-lg' %>
       
<% end %>

<%= link_to 'カテゴリー一覧に戻る', ctgs_path, class: 'baktop' %>
    
  </div>
</div>

app/views/ctgs/edit.html.erb
<div class="text-center">
    <h3>カテゴリーの編集ページ</h3>
<%= render 'form', ctg: @ctg %>

</div>

app/views/ctgs/index.html.erb
    <div class="mt-1 row">
    <div class="offset-sm-3 col-sm-6 offset-sm-3">
        <div class="text-center">　
<div class="card">
    <div class="card-header">
        カテゴリー一覧
    </div>
    <div class="card-body">


        <ul>
        
          <% @ctgs.each do |ctg| %>
            <div>
              <div class ="toprap">
                 <li class ="child"><i class="fas fa-arrow-alt-circle-right"></i> <%= link_to ctg.ctg, tchings_path(ctg_id: ctg.id) %></li>
                 <p class ="child">（<%= ctg.tchings.count %>件）</p>
                
                   <% if current_user.id ==1 %>
                      <div class="btn-group topp">
                        <%= link_to "編集", edit_ctg_path(id: ctg.id), class: 'btn btn-primary btn-sm' %>
                      </div>
                       <div class="btn-group topp">
                        <%= link_to "削除", ctg, method: :delete, data: { confirm: "このカテゴリーに紐づいた投稿もすべて削除されますがよろしいですか?" }, class: 'btn btn-danger btn-sm' %>
                       </div>
                      
                   <% end %>
                  
          <% end %>
         
        </ul>
        
        <%= paginate @ctgs %>
        
           </div>
</div>
        
        <% if current_user.id ==1 %>
        
               <div class="btn-group">
                   <%= link_to 'カテゴリーの新規登録', new_ctg_path(@ctg), class: 'btn-dark btn-sm'%>
               </div>
               
               <div class="btn-group">
                    <%= link_to '新規投稿', new_tching_path, class: 'btn btn-primary btn-sm' %>
                </div>
                
                 
           
        <% end %>
        
</div>        
       
 </div>  

</div>        
       
 </div>  

app/views/ctgs/new.html.erb
<div class="text-center">
    <h3>カテゴリー新規登録</h3>
<%= render 'form', ctg: @ctg %>

</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-0">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <% if logged_in? %>
            <a class="navbar-brand" href="/">PG Study ：<%= current_user.name %></a>
      <% else %>
             <a class="navbar-brand" href="/">PG Study</a>
      <% end %>
      
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
       <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
         <%= form_with(url: search_tchings_path, method: :get, local: true, class: "form-inline") do |f| %>
         <a style="color: white;">キーワード検索：</a>
           <%= text_field_tag :q, "", placeholder: " 検索ワードを入力！", class: "form-control mr-sm-1" %>
           <%= submit_tag "検索", class: "btn btn-info" %>
         <% end %>
         
        <% end %>
      <ul class="navbar-nav">
        <% if logged_in? %>
          
               <li class="navbar-brand"><%= link_to 'Logout', logout_path, class: 'nav-link', method: :delete %></li>
               
            <% if current_user.id !=1 %>
               <li class="navbar-brand"><%= link_to "退会", user_path(id: current_user.id), method: :delete, data: { confirm: "退会処理を実行するとこのユーザーは削除されますがよろしいですか?" }, class: 'nav-link'%></li>
            <% end %>
            
        <% else %>
         
            <li class="navbar-brand"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <li class="navbar-brand"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
             
        <% end %>
      </ul>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="card">
    <div class="card-header">
        カテゴリー一覧
    </div>
    <div class="card-body">
        <ul>
            <% Ctg.all.each do |ctg| %>
            <div>
                <li class ="child"><i class="fas fa-arrow-alt-circle-right"></i><%= link_to ctg.ctg, tchings_path(ctg_id: ctg.id) %></li>
                <p class ="child">（<%= ctg.tchings.count %>件）</p>
            </div>
            <% end %>
       </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PG Study</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
   
  </head>

  <body>
     <div id="wrapper">
        <%= render 'layouts/navbar' %>
      
        <div class="container-fluid">
           
              <%= render 'layouts/flash_messages' %>
              <%= yield %>
           
        </div>
        
      <footer>
        <div class="text-center">
            <small>&copy; 2019.Hideto Kashiyama</small>
        </div>
      </footer>
   </div>
</body>
  
  
</html>

app/views/tchings/_form.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-sm-6">
   
<%= form_with(model: @tching, local: true) do |f| %>

    <% if tching.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% tching.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    
      <div class="form-group">
       <%= f.collection_select :ctg_id, Ctg.all, :id, :ctg, { include_blank: true }, class: "select1" %>  ←カテゴリーを選択してください。
      </div>
      <div class="form-group">
      <label>タイトル：</label>
       <%= f.text_field :title, class: "form-control" %>
      </div>
     
      <div class="form-group" >
        <%= f.label :content, '詳細：' %>
        <%= f.text_area :content, class: "form-control", rows: "15"  %>
      </div>

       <%= f.submit '投稿', class: 'btn btn-primary btn-lg' %>
       
    <% end %>

    <div class="text-center">　
        <%= link_to '戻る', :back %>
    　　<%= link_to 'カテゴリー一覧に戻る', ctgs_path, class: 'baktop' %>
    </div>
  </div>
</div>

app/views/tchings/edit.html.erb
<div class="text-center">
<h3>編集ページ</h3>
</div>

<%= render 'form', tching: @tching %>

app/views/tchings/index.html.erb
<div class="container">
  <div class="mt-2 row">
    <div class="col-sm-6">

 <h3 class="cap">タイトル一覧 </h3>
  
   <% if current_user.id ==1 %>
        
        <%= link_to '新規投稿', new_tching_path(ctg_id: params[:ctg_id]), class: 'btn btn-primary btn-sm cap' %>
          
      <% end %>
   
  
      <p>（カテゴリー：<%= @ctg.ctg %>）<%= @tchings.count %>件</p>
      <ul>
        <% @tchings.each do |tching| %>
          <li><%= link_to tching.title, tching, class: 'content' %></li>
        <% end %>
      </ul>
      <%= paginate @tchings %>
     
    </div>
 
    <div class="col-sm-6">
      <%= render "layouts/sidebar" %>
    </div>
  
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to 'トップ（カテゴリー一覧に戻る）', ctgs_path, class: "baktop" %>
    </div>
  </div>
</div>

app/views/tchings/new.html.erb
<div class="text-center">
    <h3>新規投稿ページ</h3>

</div>

<%= render 'form', tching: @tching %>

app/views/tchings/serch.html.erb
<div class="container">
  <div class="mt-2 row">
    <div class="col-8">
  <h3 class= "child">タイトル一覧</h3>
  <% if current_user.id ==1 %>
        <div class="btn-toolbar child">
          <div class="btn-group">
            <%= link_to '新規投稿', new_tching_path, class: 'btn btn-primary btn-sm' %>
          </div>
        </div>
      <% end %>
      
      <p>（キーワード：<%= @keyw %>）<%= @tchings.count %>件</p>
      <ul>
        <% @tchings.each do |tching| %>
        
          <li><%= link_to tching.title, tching_path(tching, q: params[:q]), class: 'content' %></li>
          
        <% end %>
      </ul>
      <%= paginate @tchings %>
      
      
    </div>
    <div class="col-4">
      <%= render "layouts/sidebar" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= link_to 'トップ（カテゴリー一覧に戻る）', ctgs_path, class: "baktop" %>
    </div>
  </div>
</div>

app/views/tchings/show.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-sm-6">
         <div class="text-center mt-1">
          <h3 class= "child"><%= @tching.title %></h3>
         </div >
         
         <div>
        
          <% if current_user.id ==1 %>
        
             <div style="float: left">
                 
                <div class="btn-group btn-h">
                    <%= link_to '投稿を編集する', edit_tching_path(@tching) ,class: 'btn btn-primary btn-sm'%>
                 </div>  
                 <div class="btn-group btn-h">
                    <%= link_to '投稿を削除する', @tching, method: :delete, data: { confirm: '本当に削除してよろしいですか？' },class: 'btn btn-danger btn-sm' %>
                  </div>
                  
             </div>
            
            <div style="text-align: right">
                
                  <% if params[:q] != nil %>
       
                        <%= link_to 'タイトル一覧に戻る', search_tchings_path(q: params[:q]) %>
                  <% else %>    
                       <%= link_to 'タイトル一覧に戻る', tchings_path(ctg_id: @ctg_id) %>
                  <% end %>   
        
               <div class="btn-group btn-h">
                        <%= link_to '新規投稿', new_tching_path(@ctg), class: 'btn btn-primary btn-sm' %>
               </div>
               
             </div>
           
          <% end %>
      
       </div>
       
    <div> 
 
<div class="tb">
    
    <% urchgtext = text_url_to_link(simple_format(h(@tching.content))).html_safe %>
    <%= urchgtext %>

</div>

    <div class="text-center m-2">
        
      <!-- <%= form_with(url: search_tchings_path, method: :get, local: true, class: "form-inline") do |f| %>
        
           <%= hidden_field_tag :q, params[:q] %>
           <%= submit_tag "タイトル一覧に戻る" %>
           
       <% end %>-->
       
          
          
               <%= link_to 'カテゴリー一覧に戻る', ctgs_path, class: 'baktop' %>
       
    </div>
 
 </div>
</div>

 

app/views/toppages/index.html.erb
<% if logged_in? %>
  <%= link_to 'カテゴリー一覧へ', ctgs_path, class: 'btn btn-lg btn-primary' %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the PGStudy</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

  

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>